"""
Django settings for theway project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8l@ha((y7^)bn@z=c2xl_6=trp(a+i=$#*bcl#$dew(0v$@@z2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'theway.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'theway.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
# Storage setting to minio
# STORAGES = {
#     "default": {"BACKEND": "storages.backends.s3.S3Storage"},
#     "staticfiles": {"BACKEND": 'storages.backends.s3.S3Storage'},
#     "OPTIONS": {
#         'access_key':'TNnsTWCNlKhUmaDg',
#         'bucket_name' :'company',
#         'secret_key':'u2vI03EyYcIbqhDlPdxtzvrC5GOs1pFv',
#         'custom_domain ':"http://env-8091859.ktm.yetiappcloud.com:4949",
#         'use_ssl' :False
#         },

#     }

# STATICFILES_LOCATION = 'static'
# MEDIAFILES_LOCATION = 'media'
# MEDIA_URL = 'http://env-8091859.ktm.yetiappcloud.com:4949/media/'
# MEDIA_ROOT = 'http://env-8091859.ktm.yetiappcloud.com:4949/media/'
# STATIC_URL = 'http://env-8091859.ktm.yetiappcloud.com:4949/media/'
# STATIC_ROOT = 'http://env-8091859.ktm.yetiappcloud.com:4949/statci/'

STATICFILES_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

AWS_ACCESS_KEY_ID = "TNnsTWCNlKhUmaDg",
AWS_SECRET_ACCESS_KEY = "u2vI03EyYcIbqhDlPdxtzvrC5GOs1pFv",
AWS_STORAGE_BUCKET_NAME = "company",
AWS_S3_ENDPOINT_URL="http://env-8091859.ktm.yetiappcloud.com:4949",
AWS_S3_USE_SSL=False


# AWS_STORAGE_BUCKET_NAME = "company"

# AWS_S3_ENDPOINT_URL="http://env-8091859.ktm.yetiappcloud.com/4949"
# AWS_S3_USE_SSL=False
# # AWS_S3_CUSTOM_DOMAIN
# # Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'


# MEDIA_URL = 'http://env-8091859.ktm.yetiappcloud.com:4949/media/'
# STATIC_URL = 'http://env-8091859.ktm.yetiappcloud.com:4949/static/'


  # Local directory where media files are stored temporarily

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
